### ISSUE TITLE
Nitda blockchain scholarship

### ISSUE THREAD

**Issue by aliyu2468** [calistus-igwilo/nitda-blockchain-scholarship#80]

**Comment by Uymadawaki** [comment]
Good morning

**Comment by aliyu2468** [comment]
Good morning

**Comment by Sambozee** [comment]
Hello Mr Calistus, thank you for the tutorial. When I logged into my github account i tried following your instruction of adding nitda-blockchain-scholarship to my profile link but it wasnt coming up. pls is there anything am doing wrong because i cannot also see the fork on your timeline when i try to open it?
